In [1]:

######## snakemake preamble start (automatically inserted, do not edit) ########
import sys; sys.path.extend(['/home/mielliott/mambaforge/envs/snakemake/lib/python3.12/site-packages', '/home/mielliott/biodiversity-llms/biodiversity-confidence/workflow/modules', '/home/mielliott/biodiversity-llms/biodiversity-confidence/workflow/rules', '/home/mielliott/biodiversity-llms/biodiversity-confidence/workflow', '/home/mielliott/mambaforge/envs/snakemake/bin', '/home/mielliott/mambaforge/envs/snakemake/lib/python3.12', '/home/mielliott/mambaforge/envs/snakemake/lib/python3.12/lib-dynload', '/home/mielliott/mambaforge/envs/snakemake/lib/python3.12/site-packages', '/home/mielliott/.cache/snakemake/snakemake/source-cache/runtime-cache/tmp1v2tvpl5/file/home/mielliott/biodiversity-llms/biodiversity-confidence/workflow/rules/../notebooks', '/home/mielliott/biodiversity-llms/biodiversity-confidence/workflow/rules/../notebooks']); import pickle; snakemake = pickle.loads(b'\x80\x04\x95\xa1\x0e\x00\x00\x00\x00\x00\x00\x8c\x10snakemake.script\x94\x8c\tSnakemake\x94\x93\x94)\x81\x94}\x94(\x8c\x05input\x94\x8c\x0csnakemake.io\x94\x8c\nInputFiles\x94\x93\x94)\x81\x94(\x8c\x1cresults/input/alignments.tsv\x94\x8c\x1bresults/input/bad-names.tsv\x94\x8c1results/gpt-3.5-turbo-0613/taxonomy/responses.tsv\x94e}\x94(\x8c\x06_names\x94}\x94(\x8c\nalignments\x94K\x00N\x86\x94\x8c\tbad_names\x94K\x01N\x86\x94\x8c\tresponses\x94K\x02N\x86\x94u\x8c\x12_allowed_overrides\x94]\x94(\x8c\x05index\x94\x8c\x04sort\x94eh\x18\x8c\tfunctools\x94\x8c\x07partial\x94\x93\x94h\x06\x8c\x19Namedlist._used_attribute\x94\x93\x94\x85\x94R\x94(h\x1e)}\x94\x8c\x05_name\x94h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh\x10h\nh\x12h\x0bh\x14h\x0cub\x8c\x06output\x94h\x06\x8c\x0bOutputFiles\x94\x93\x94)\x81\x94(\x8c1results/gpt-3.5-turbo-0613/taxqa-results.py.ipynb\x94\x8c/results/gpt-3.5-turbo-0613/taxonomy/summary.tsv\x94e}\x94(h\x0e}\x94(\x8c\x08notebook\x94K\x00N\x86\x94\x8c\x07summary\x94K\x01N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh0h,h2h-ub\x8c\x06params\x94h\x06\x8c\x06Params\x94\x93\x94)\x81\x94(]\x94(\x8cWDoes {genus} {specificepithet} naturally occur in {county}, {stateprovince}, {country}?\x94\x8cWCan species {genus} {specificepithet} be found in {county}, {stateprovince}, {country}?\x94\x8cfIs it possible to encounter species {genus} {specificepithet} in {county}, {stateprovince}, {country}?\x94\x8ceIs there a presence of species {genus} {specificepithet} within {county}, {stateprovince}, {country}?\x94\x8cSDoes {county}, {stateprovince}, {country} harbor species {genus} {specificepithet}?\x94\x8cUIs species {genus} {specificepithet} present in {county}, {stateprovince}, {country}?\x94\x8cZCan one observe species {genus} {specificepithet} in {county}, {stateprovince}, {country}?\x94e]\x94(\x8c\x07kingdom\x94\x8c\x06phylum\x94\x8c\x06family\x94\x8c\x05genus\x94\x8c\x0fspecificepithet\x94\x8c\x07country\x94\x8c\rstateprovince\x94\x8c\x06county\x94eJ\xd7\x10\x01\x00\x88e}\x94(h\x0e}\x94(\x8c\tphrasings\x94K\x00N\x86\x94\x8c\x0cquery_fields\x94K\x01N\x86\x94\x8c\x04seed\x94K\x02N\x86\x94\x8c\x11validate_absences\x94K\x03N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bhThAhVhIhXJ\xd7\x10\x01\x00hZ\x88ub\x8c\twildcards\x94h\x06\x8c\tWildcards\x94\x93\x94)\x81\x94}\x94(h\x0e}\x94h\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bub\x8c\x07threads\x94K\x01\x8c\tresources\x94h\x06\x8c\tResources\x94\x93\x94)\x81\x94(K\x01K\x01\x8c\x04/tmp\x94e}\x94(h\x0e}\x94(\x8c\x06_cores\x94K\x00N\x86\x94\x8c\x06_nodes\x94K\x01N\x86\x94\x8c\x06tmpdir\x94K\x02N\x86\x94uh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh|K\x01h~K\x01h\x80hyub\x8c\x03log\x94h\x06\x8c\x03Log\x94\x93\x94)\x81\x94\x8c1results/gpt-3.5-turbo-0613/taxqa-results.py.ipynb\x94a}\x94(h\x0e}\x94h0K\x00N\x86\x94sh\x16]\x94(h\x18h\x19eh\x18h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x18sNt\x94bh\x19h\x1ch\x1e\x85\x94R\x94(h\x1e)}\x94h"h\x19sNt\x94bh0h\x8fub\x8c\x06config\x94}\x94(\x8c\x03llm\x94\x8c\x12gpt-3.5-turbo-0613\x94\x8c\x0brandom_seed\x94J\xd7\x10\x01\x00\x8c\trecordset\x94\x8c+hash://md5/8f0594be7f88e4fc7b30c0854e7ca029\x94\x8c\x02qa\x94}\x94(\x8c\x08defaults\x94}\x94(\x8c\x07command\x94\x8c-python3 ~/biodiversity-llms/scripts/nlp/qa.py\x94\x8c\x07shuffle\x94\x88\x8c\x0bquery_limit\x94K\x01\x8c\nbatch_size\x94K\x01u\x8c\noccurrence\x94}\x94(\x8c\x03llm\x94h\x9fh\xa7h\xa8h\xa9\x89h\xaaK\x00h\xabKd\x8c\x05input\x94\x8c\x15results/input/all.tsv\x94\x8c\x04args\x94]\x94(\x8c\x0e--max-tokens 1\x94\x8c\x0c--timeout 10\x94\x8c\x12--num-responses 10\x94\x8c\x13--combine-responses\x94e\x8c\x0cquery_fields\x94]\x94(hJhKhLhMhNhOhPhQe\x8c\x0fquery_templates\x94hA\x8c\x0cquery_suffix\x94\x8c\x17Only respond yes or no.\x94\x8c\noutput_dir\x94\x8c%results/gpt-3.5-turbo-0613/occurrence\x94u\x8c\x08taxonomy\x94}\x94(h\xaeh\x9fh\xa7h\xa8h\xa9\x89h\xaaK\x00h\xabKd\x8c\x05input\x94\x8c\x1dresults/input/taxonomy-qa.tsv\x94\x8c\x04args\x94]\x94(\x8c\x0f--max-tokens 10\x94\x8c\x0c--timeout 10\x94\x8c\x12--num-responses 10\x94\x8c\x13--combine-responses\x94\x8c\x12--escape-responses\x94e\x8c\x0cquery_fields\x94]\x94(\x8c\x0csubject_rank\x94\x8c\x0bobject_rank\x94\x8c\x05taxon\x94\x8c\x07kingdom\x94\x8c\x06phylum\x94\x8c\x05class\x94\x8c\x05order\x94\x8c\x06family\x94\x8c\x05genus\x94e\x8c\x0fquery_templates\x94]\x94\x8cGWhat taxonomic {object_rank} does {subject_rank} \\"{taxon}\\" belong to?\x94a\x8c\x0cquery_suffix\x94\x8c\x1dOnly say its scientific name.\x94h\xbc\x8c#results/gpt-3.5-turbo-0613/taxonomy\x94u\x8c\x04test\x94}\x94(h\xae\x8c\tllama2-7b\x94h\xa7h\xa8h\xa9\x88h\xaaK\x01h\xabK\x01\x8c\x05input\x94\x8c\x17resources/test-data.tsv\x94\x8c\x04args\x94]\x94(\x8c\x10--max-tokens 100\x94\x8c\x0c--timeout 10\x94\x8c\x11--num-responses 2\x94e\x8c\x0cquery_fields\x94]\x94\x8c\x07species\x94a\x8c\x0fquery_templates\x94]\x94\x8c\x16How do {species} know?\x94a\x8c\x0cquery_suffix\x94\x8c\x1cExplain it to me like I\'m 5.\x94h\xbc\x8c\x16results/llama2-7b/test\x94uu\x8c\x07results\x94}\x94(\x8c\x08notebook\x94\x8c\x14results-gpt.py.ipynb\x94\x8c\x0brandom_seed\x94J\xd7\x10\x01\x00\x8c\x11validate_absences\x94\x88\x8c\x15train_test_split_rank\x94\x8c\x06family\x94\x8c\x13split_test_fraction\x94G?\xe0\x00\x00\x00\x00\x00\x00u\x8c\x07preston\x94}\x94\x8c\x07remotes\x94]\x94(\x8c\x12https://zenodo.org\x94\x8c\x12https://linker.bio\x94es\x8c\x08defaults\x94h\x9du\x8c\x04rule\x94\x8c\x15taxqa_analyze_results\x94\x8c\x0fbench_iteration\x94N\x8c\tscriptdir\x94\x8cU/home/mielliott/biodiversity-llms/biodiversity-confidence/workflow/rules/../notebooks\x94ub.'); from snakemake.logging import logger; logger.printshellcmds = False; import os; os.chdir(r'/home/mielliott/biodiversity-llms/biodiversity-confidence');
######## snakemake preamble end #########

In [2]:
import pandas as pd
import numpy as np
import textdistance as td
from typing import NamedTuple

In [3]:
class InputFiles(NamedTuple):
    responses: str
    alignments: str
    bad_names: str

class OutputFiles(NamedTuple):
    summary: str

class Env(NamedTuple):
    input_files: InputFiles
    output_files: OutputFiles

if "snakemake" in globals():
    env = Env(
        input_files=snakemake.input,
        output_files=snakemake.output
    )
else: # Fill in parameters manually for testing outside of snakemake
    import os
    ROOT = os.path.expanduser("~/biodiversity-llms")
    LLM = "gpt-3.5-turbo-0613" #"gpt-4-1106-preview"

    env = Env(
        input_files = InputFiles(
            responses=f"../../results/{LLM}/taxonomy/responses.tsv",
            alignments="../../results/input/alignments.tsv",
            bad_names="../../results/input/bad-names.tsv"
        ),
        output_files = OutputFiles(
            summary=f"../../results/{LLM}/taxonomy_performance.tsv"
        )
    )

def nest(level, strings):
    separator = "\n" + "  " * level + "- "
    return separator + separator.join([str(s) for s in strings])

def quote(strings):
    return [f'"{s}"' for s in strings]

print("Job parameters:")
print(env)

Job parameters:
Env(input_files=['results/input/alignments.tsv', 'results/input/bad-names.tsv', 'results/gpt-3.5-turbo-0613/taxonomy/responses.tsv'], output_files=['results/gpt-3.5-turbo-0613/taxqa-results.py.ipynb', 'results/gpt-3.5-turbo-0613/taxonomy/summary.tsv'])

In [4]:
env.input_files

['results/input/alignments.tsv',
 'results/input/bad-names.tsv',
 'results/gpt-3.5-turbo-0613/taxonomy/responses.tsv']

In [5]:
for k in env.input_files:
    print(k)

results/input/alignments.tsv
results/input/bad-names.tsv
results/gpt-3.5-turbo-0613/taxonomy/responses.tsv

In [6]:
GARBAGE_WORDS = {
    "the",
    "only",
    "that",
    "this",
    "sorry",
    "there",
    "theres",
    "apologies",
}

bad_names = pd.read_csv(env.input_files.bad_names, sep="\t", dtype=str)\
    .set_index("providedName").index.str.lower().union([""])

def clean_response(response: str, object_rank: str):
    response = response.lower()
    s = str(response).split()[0] # Get the first word

    # For responses like "Phylum: Mollusca", use the second word instead
    if s[-1] == ":" or s == object_rank:
        s = str(response).split()[1]

    s = "".join([c for c in s if c.isalpha()]) # Filter out non-letters
    return s

def clean_response_list(responses: pd.Series, subject: str, object_rank: str):
    return list(filter(lambda x: not is_garbage_response(x, subject, object_rank), [clean_response(a, object_rank) for a in responses]))

def is_garbage_response(response, subject, object_rank):
    response = clean_response(response, object_rank)
    return response == subject or len(response) <= 2 or response in GARBAGE_WORDS

def mark_garbage_responses(responses, subject, object_rank):
    return map(lambda x: is_garbage_response(x, subject, object_rank), responses)

def clean_taxa(name):
    name = name.split()
    return "".join(filter(str.isalpha, name))
    
conv = {
    "taxon": clean_taxa,
    "responses": eval
}

responses = pd.read_csv(env.input_files.responses, sep="\t", converters=conv)
responses = responses[responses["kingdom"].isin(("animalia", "plantae"))]
responses = responses.drop(columns=["query", "question number", "input token count", "output token count"])
responses = responses[~responses["taxon"].isin(bad_names)]

responses["garbage responses"] = responses.apply(axis=1, func=lambda x: sum(mark_garbage_responses(x["responses"], x["taxon"], x["object_rank"])))
responses["responses"] = responses.apply(axis=1, func=lambda x: clean_response_list(x["responses"], x["taxon"], x["object_rank"]))

scores = responses.copy()
responses.head(3)

,subject_rank,object_rank,taxon,kingdom,phylum,class,order,family,genus,responses,garbage responses
0,phylum,kingdom,annelida,animalia,NaN,NaN,NaN,NaN,NaN,"[animalia, animalia, animalia, animalia, anima...",0
1,phylum,kingdom,arthropoda,animalia,NaN,NaN,NaN,NaN,NaN,"[animalia, animalia, animalia, animalia, anima...",3
2,phylum,kingdom,brachiopoda,animalia,NaN,NaN,NaN,NaN,NaN,"[animalia, animalia, animalia, animalia, anima...",0

### Score against Nomer alignment

In [7]:
# Nomer alignment
conv = {
    "aliases": eval,
    "classification": eval
}

alignment = pd.read_csv(env.input_files.alignments, sep="\t", index_col=0, converters=conv)
alignment.head(3)

,aliases,classification
name,,
abrothrix,{abrothrix},"{(family, cynodontia), (subclass, eutheria), (..."
acacia,"{acacia, hantavirus}","{(phylum, charophyta), (, spermatophyta), (cla..."
acaciella,{acaciella},"{(, spermatophyta), (clade, gunneridae), (clad..."

In [8]:
def score_partial_match(response, name):
    return td.jaro_winkler(response, name, prefix_weight=0.2)

def score_best_partial_match_any_rank(response, full_classification):
    best_score = 0
    best_match = None
    for rank, name in full_classification:
        score = score_partial_match(response, name)
        if score > best_score:
            best_score = score
            if score >= 1:
                return 1
    return best_score

row = responses.loc[300]

def nomer_partial_match_scores(row):
    taxon = row["taxon"]
    if taxon in alignment.index:
        classification = alignment.loc[row["taxon"]]["classification"]
        scores = list(map(lambda r: score_best_partial_match_any_rank(r, classification), row["responses"]))
    else:
        scores = list()

    return pd.Series({
        "partial match best": np.max(scores) if len(scores) > 0 else np.nan,
        "partial match mean": np.mean(scores),
        "partial match var": np.var(scores),
    })

nomer_partial_match_scores(row)

partial match best    1.000000
partial match mean    0.980635
partial match var     0.003000
dtype: float64

In [9]:
def nomer_exact_match(subject, rank, response, classification):
    if subject in alignment.index:
        return 1.0 if any([x[1] == response for x in classification if x[0] == rank]) else 0.0
    else:
        return np.nan

def nomer_exact_match_at_any_rank(subject, response, classification):
    if subject in alignment.index:
        return 1.0 if any([x[1] == response for x in classification]) else 0.0
    else:
        return np.nan

def nomer_rank_exact_match_scores(row):
    taxon = row["taxon"]
    if taxon in alignment.index:
        classification = alignment.loc[row["taxon"]]["classification"]
        scores = list(map(lambda r: nomer_exact_match(row["taxon"], row["object_rank"], r, classification), row["responses"]))
    else:
        scores = list()

    return pd.Series({
        "rank exact match best": np.max(scores) if len(scores) > 0 else np.nan,
        "rank exact match mean": np.mean(scores)
    })

def nomer_any_exact_match_scores(row):
    taxon = row["taxon"]
    if taxon in alignment.index:
        classification = alignment.loc[row["taxon"]]["classification"]
        scores = list(map(lambda r: nomer_exact_match_at_any_rank(row["taxon"], r, classification), row["responses"]))
    else:
        scores = list()

    return pd.Series({
        "any exact match best": np.max(scores) if len(scores) > 0 else np.nan,
        "any exact match mean": np.mean(scores)
    })

In [10]:
scores = scores.join(scores.apply(axis=1, func=nomer_partial_match_scores))
scores = scores.join(scores.apply(axis=1, func=nomer_rank_exact_match_scores))
scores = scores.join(scores.apply(axis=1, func=nomer_any_exact_match_scores))

/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3787: RuntimeWarning: Degrees of freedom <= 0 for slice
  return _methods._var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/_methods.py:163: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/_methods.py:198: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/home/mielliott/biodiversity-llms/biodiversity-confidence/.snakemake/conda/38888eb1e14f3f8cdbf82243dad7dc5a_/lib/python3.12/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)

In [11]:
scores.head(3)

,subject_rank,object_rank,taxon,kingdom,phylum,class,order,family,genus,responses,garbage responses,partial match best,partial match mean,partial match var,rank exact match best,rank exact match mean,any exact match best,any exact match mean
0,phylum,kingdom,annelida,animalia,NaN,NaN,NaN,NaN,NaN,"[animalia, animalia, animalia, animalia, anima...",0,1.0,1.0,0.0,1.0,1.0,1.0,1.0
1,phylum,kingdom,arthropoda,animalia,NaN,NaN,NaN,NaN,NaN,"[animalia, animalia, animalia, animalia, anima...",3,1.0,1.0,0.0,1.0,1.0,1.0,1.0
2,phylum,kingdom,brachiopoda,animalia,NaN,NaN,NaN,NaN,NaN,"[animalia, animalia, animalia, animalia, anima...",0,1.0,1.0,0.0,1.0,1.0,1.0,1.0

In [12]:
only_scores = scores[scores["partial match best"] >= 0]

In [13]:
only_scores.groupby("subject_rank")[['garbage responses',
       'partial match best', 'partial match mean', 'partial match var',
       'rank exact match best', 'rank exact match mean',
       'any exact match best', 'any exact match mean']].mean().loc[['phylum', 'class', 'order', 'family', 'genus']]\
              .map(lambda x: f"{x:.2}")

,garbage responses,partial match best,partial match mean,partial match var,rank exact match best,rank exact match mean,any exact match best,any exact match mean
subject_rank,,,,,,,,
phylum,0.67,1.0,1.0,6.8e-06,1.0,0.99,1.0,0.99
class,1.4,0.99,0.98,0.00016,0.95,0.93,0.96,0.94
order,2.3,0.99,0.98,0.0017,0.89,0.83,0.93,0.89
family,2.8,0.98,0.98,0.00091,0.9,0.85,0.91,0.89
genus,3.0,0.97,0.97,0.00079,0.81,0.75,0.87,0.85

In [14]:
only_scores.groupby("object_rank")[['garbage responses',
       'partial match best', 'partial match mean', 'partial match var',
       'rank exact match best', 'rank exact match mean',
       'any exact match best', 'any exact match mean']].mean().loc[['kingdom', 'phylum', 'class', 'order', 'family']]\
              .map(lambda x: f"{x:.2}")

,garbage responses,partial match best,partial match mean,partial match var,rank exact match best,rank exact match mean,any exact match best,any exact match mean
object_rank,,,,,,,,
kingdom,1.3,0.98,0.97,0.0014,0.94,0.91,0.94,0.92
phylum,3.5,0.97,0.96,0.00076,0.68,0.59,0.84,0.81
class,3.5,0.97,0.97,0.00056,0.79,0.71,0.88,0.86
order,3.7,0.98,0.97,0.00052,0.81,0.76,0.86,0.84
family,3.5,0.98,0.97,0.00063,0.84,0.81,0.85,0.82

In [15]:
only_scores.groupby(["subject_rank", "object_rank"])[['rank exact match mean',
       'any exact match mean']].mean().sort_values("rank exact match mean", ascending=False)\
              .map(lambda x: f"{x:.0%}")

                         rank exact match mean any exact match mean
subject_rank object_rank
phylum       kingdom                       99%                  99%
family       kingdom                       97%                 100%
class        kingdom                       95%                  97%
order        phylum                        93%                  93%
genus        kingdom                       91%                  91%
class        phylum                        90%                  90%
family       phylum                        84%                  89%
             class                         82%                  83%
genus        family                        81%                  82%
order        kingdom                       77%                  94%
             class                         77%                  78%
genus        order                         76%                  84%
family       order                         75%                  78%
genus        class                         70%                  86%
             phylum                        56%                  80%

In [16]:
summary = only_scores.groupby(["subject_rank", "taxon"])[['garbage responses',
       'partial match best', 'partial match mean', 'partial match var',
       'rank exact match best', 'rank exact match mean',
       'any exact match best', 'any exact match mean']].mean()
summary.map(lambda x: f"{x:.0%}")

                            garbage responses partial match best  \
subject_rank taxon
class        actinopterygii              300%               100%
             amphibia                    150%               100%
             angiospermae                  0%               100%
             anthozoa                      0%               100%
             articulata                   50%                90%
...                                       ...                ...
phylum       mollusca                      0%               100%
             porifera                      0%               100%
             rhodophyta                  200%               100%
             spermatophyta                 0%               100%
             tracheophyta                  0%               100%

                            partial match mean partial match var  \
subject_rank taxon
class        actinopterygii               100%                0%
             amphibia                     100%                0%
             angiospermae                 100%                0%
             anthozoa                     100%                0%
             articulata                    90%                0%
...                                        ...               ...
phylum       mollusca                     100%                0%
             porifera                     100%                0%
             rhodophyta                   100%                0%
             spermatophyta                100%                0%
             tracheophyta                 100%                0%

                            rank exact match best rank exact match mean  \
subject_rank taxon
class        actinopterygii                  100%                  100%
             amphibia                        100%                  100%
             angiospermae                    100%                  100%
             anthozoa                        100%                  100%
             articulata                       50%                   50%
...                                           ...                   ...
phylum       mollusca                        100%                  100%
             porifera                        100%                  100%
             rhodophyta                      100%                   88%
             spermatophyta                   100%                  100%
             tracheophyta                    100%                  100%

                            any exact match best any exact match mean
subject_rank taxon
class        actinopterygii                 100%                 100%
             amphibia                       100%                 100%
             angiospermae                   100%                 100%
             anthozoa                       100%                 100%
             articulata                      50%                  50%
...                                          ...                  ...
phylum       mollusca                       100%                 100%
             porifera                       100%                 100%
             rhodophyta                     100%                  88%
             spermatophyta                  100%                 100%
             tracheophyta                   100%                 100%

[2062 rows x 8 columns]

In [17]:
summary.to_csv(env.output_files.summary, sep="\t")